image:
  tag: "4.4.1"
usePassword: false
serviceAccount:
  create: false
persistence:
  enabled: false
useStatefulSet: false
resources:
  requests:
    cpu: "1"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "2Gi"
labels:
  branch: "$BRANCH_NAME"
  resource: deployment
  team: platform
  usage: "$USAGE"
podLabels:
  branch: "$BRANCH_NAME"
  resource: pod
  team: platform
  usage: "$USAGE"
tolerations:
  - key: team
    operator: Equal
    value: platform
    effect: NoSchedule
nodeSelector:
  team: platform
